// <auto-generated />
namespace NewsEngine2A.Context.Config
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class identityClassic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityClassic));
        
        string IMigrationMetadata.Id
        {
            get { return "201912151807252_identityClassic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
